version: '3.4'

services:
  blazor:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:64103;http://+:80
    volumes:
      - ~/.aspnet/https:/https:ro
      - /C/ei8/avatars/dev/test:/C/db
    ports:
      - 192.168.0.104:64103:64103
networks:
    default:
        external:
            name: sample_default